In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
arr=np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [5]:
arr=np.zeros((1,2))
print(arr)

[[0. 0.]]


In [6]:
arr=np.ones(3)
print(arr)

[1. 1. 1.]


In [7]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr=np.empty(2)
print(arr)

[0. 0.]


In [9]:
arr=np.empty((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
arr=np.array(3)
print(arr)

3


In [13]:
arr=np.ones(3)
print(arr)

[1. 1. 1.]


In [14]:
arr=np.array([1,2,3])
print(arr.dtype)

int32


In [15]:
arr=np.array([1.,2.,3.])
print(arr.dtype)

float64


In [16]:
arr=np.array([1,2,3],dtype=np.float64)
print(arr.dtype)

float64


In [17]:
arr=np.arange(2)
print(arr)

[0 1]


In [18]:
arr=np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
arr=np.arange(12).respace(2,3)
print(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'respace'

In [20]:
arr=np.arange(12).respace((3,2))
print(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'respace'

In [21]:
arr=random.randn(3)
print(arr)

NameError: name 'random' is not defined

In [22]:
arr=np.random.randn(3)
print(arr)

[ 1.73194329  0.15774957 -0.38174384]


In [23]:
arr=np.arange(12).reshape(2,3)
print(arr)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [27]:
arr=np.arange(12)
arr1=arr.reshape(3,4)
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
arr=np.arange(10)
arr1=arr.reshape(2,5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
arr=np.arange(12)
arr1=arr.flatten()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [30]:
arr=np.arange(12)
arr1=arr.ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr1=arr.flatten()
print(arr1)

[1 2 3 4 5 6 7 8]


In [34]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr1=arr.ravel()
print(arr1)

[1 2 3 4 5 6 7 8]


In [35]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr1=arr.flatten()
arr1[2]=50
print(arr1)

[ 1  2 50  4  5  6  7  8]


In [36]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr1=arr.ravel()
arr1[1]=100
print(arr1)

[  1 100   3   4   5   6   7   8]


In [37]:
arr=np.arange(12)
print(arr[:7])

[0 1 2 3 4 5 6]


In [38]:
arr=np.arange(34)
print(arr[6:20])

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [41]:
arr=np.arange(23)
print(arr[20:6:-2])

[20 18 16 14 12 10  8]


In [45]:
arr1=np.array([[1,2,3],[4,12,13]])
arr2=np.array([[6,17,8],[14,5,16]])
g=arr1>arr2
l=arr1<arr2
e=arr1==arr2
print(g)
print(l)
print(e)

[[False False False]
 [False  True False]]
[[ True  True  True]
 [ True False  True]]
[[False False False]
 [False False False]]


In [46]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
r=np.equal(arr1,arr2)
print(r)

[False False False]


In [49]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,-1])

3


In [50]:
arr=np.array([1,2,3,4,5])
arr1=arr.astype('f')
print(arr1)

[1. 2. 3. 4. 5.]


In [58]:
arr1=np.array([1,2,3])
arr2=np.array([1.,2.,3.])
arr=arr1.astype(arr2.dtype)
print(arr)

[1. 2. 3.]


In [52]:
arr=np.arange(12)
arr1=arr.reshape((4,3),order='F')
print(arr1)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [53]:
arr=np.arange(12)
arr[2:]=10
print(arr)

[ 0  1 10 10 10 10 10 10 10 10 10 10]


In [54]:
arr=np.arange(12)
arr[::3]=50
print(arr)

[50  1  2 50  4  5 50  7  8 50 10 11]


In [64]:
arr=np.array([[1,2,3,4,5,15,17,18,20],[6,7,8,9,10,11,31,18,21]])
arr1=arr.reshape(3,-1)
print(arr1)

[[ 1  2  3  4  5 15]
 [17 18 20  6  7  8]
 [ 9 10 11 31 18 21]]


In [65]:
a=np.arange(12)
b=a.reshape(3,4)
c=b>4
print(c)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [66]:
arr=np.arange(12)
print(np.transpose(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
